openapi: 3.0.0
info:
    title: Simple express app
    description: A simple api to familiarise myself with LEGO tools
    version: 1.0.0

  
servers:
    - url: localhost:3000/
paths:
  /health:
    get:
      summary: Shows healthcheck message
      responses:
        '200':
          description: Success
          content:
            application/json:
                schema:
                    properties:
                        status:
                            type: string
                            example: OK
  /books:
      get:
        summary: Returns a list of all books
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      author:
                        type: string
      post:
        summary: Returns book that was created
        responses:
          201:
            description: Created 
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      author:
                        type: string
  /book/{bookId}:
    get:
      summary: Returns a book with a specific bookId
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  author:
                    type: string          
    delete:
      summary: Deletes a book with a specific bookId
      responses:
        204:
          description: Book succesfully removed
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  author:
                    type: string          




